# Generated by Django 4.1.3 on 2022-12-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EAM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='decrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
                ('is_last_decrease', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='increase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('is_first_increase', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('asset_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('administrator', models.CharField(blank=True, max_length=30, null=True)),
                ('increase_or_decrease', models.CharField(choices=[('新增', '新增'), ('减少', '减少')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=30, null=True)),
                ('system_classification', models.CharField(blank=True, max_length=30, null=True)),
                ('system_grading', models.CharField(blank=True, max_length=30, null=True)),
                ('administrator', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset',
            new_name='asset_name',
        ),
        migrations.CreateModel(
            name='Weak_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_type', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAM.asset')),
            ],
        ),
        migrations.CreateModel(
            name='vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.CharField(max_length=30)),
                ('is_fix', models.CharField(choices=[('修复', '修复'), ('未修复', '未修复')], max_length=30)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAM.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ip_port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAM.asset')),
            ],
        ),
    ]
